title: Manas Tiwari
description: Personal website and blog
url: "https://tiwarimanas.github.io"
collections:
  me:
    output: true
    permalink: /me/:path/
markdown: kramdown
theme: null
plugins:
  - jekyll-seo-tag
