title: Manas Tiwari
description: Personal website and blog
url: "https://tiwarimanas.github.io"
collections:
  me:
    output: true
    permalink: /me/:path/
defaults:
  - scope:
      path: ""
      type: "me"
    values:
      layout: "post"
markdown: kramdown
kramdown:
  math_engine: mathjax
theme: null
plugins:
  - jekyll-seo-tag
